# Generated by Django 5.2 on 2025-05-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0008_alter_administrador_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
