services:
  - type: web
    name: punto-fitness
    env: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn punto_fitness.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: VIRTUAL_ENV
        value: /opt/render/project/src/.venv
      - key: PATH
        value: /opt/render/project/src/.venv/bin:$PATH
      - key: DATABASE_URL
        fromDatabase:
          name: punto-fitness-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: punto_fitness.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000 