# Generated by Django 5.2.2 on 2025-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
