# Generated by Django 5.2.4 on 2025-07-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='punto_app.establecimiento'),
        ),
    ]
