# Generated by Django 5.2 on 2025-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=100),
        ),
    ]
