# Generated by Django 5.2.2 on 2025-06-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha_hora_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
