# Generated by Django 4.2.6 on 2025-05-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Activo', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='categoriaproducto',
            table='categoria_producto',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='clientemembresia',
            table='cliente_membresia',
        ),
        migrations.AlterModelTable(
            name='compravendedor',
            table='compra_vendedor',
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalle_compra',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='encargado',
            table='encargado',
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table='establecimiento',
        ),
        migrations.AlterModelTable(
            name='membresia',
            table='membresia',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='metodo_pago',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='registroacceso',
            table='registro_acceso',
        ),
        migrations.AlterModelTable(
            name='tipodocumentopago',
            table='tipo_documento_pago',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='vendedor',
        ),
        migrations.AlterModelTable(
            name='ventacliente',
            table='venta_cliente',
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_app.establecimiento')),
            ],
            options={
                'db_table': 'maquina',
            },
        ),
    ]
