# Generated by Django 5.2 on 2025-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
