# Generated by Django 5.2.2 on 2025-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0002_alter_registroacceso_fecha_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(default='Activo', max_length=30),
        ),
    ]
