# Generated by Django 5.2.2 on 2025-06-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0002_alter_registroacceso_fecha_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(default='Activo', max_length=30),
        ),
    ]
