# Generated by Django 5.2.2 on 2025-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0003_producto_imagen_alter_curso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
