# Generated by Django 5.2.2 on 2025-06-12 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0003_alter_curso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionCorreo',
            fields=[
                ('id_verificacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='punto_app.cliente')),
            ],
            options={
                'verbose_name': 'Verificación de correo',
                'verbose_name_plural': 'Verificaciones de correo',
                'db_table': 'verificacion_correo',
            },
        ),
    ]
