# Generated by Django 4.2.6 on 2025-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0003_curso_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
    ]
