# Generated by Django 5.2 on 2025-05-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0009_alter_categoriaproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='punto_app.cliente'),
        ),
    ]
