# Generated by Django 5.2 on 2025-05-30 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0011_remove_administrador_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='punto_app.cliente'),
            preserve_default=False,
        ),
    ]
