# Generated by Django 5.2 on 2025-06-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0012_administrador_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cupos', models.IntegerField()),
                ('fecha_realizacion', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_app.establecimiento')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_app.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_app.cliente')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
    ]
