# Generated by Django 5.2 on 2025-06-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0013_remove_administrador_cliente_curso_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='punto_app.cliente'),
        ),
    ]
