# Generated by Django 5.2 on 2025-06-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0014_administrador_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
