# Generated by Django 5.2.2 on 2025-06-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_app', '0015_rename_id_cliente_administrador_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'curso', 'fecha_realizacion')},
        ),
    ]
